#!/bin/bash

# check the file

if [ ! -f "minicalc.c" ]
then
	echo "Error: missing file"
	exit 1
fi

gcc minicalc.c -o minicalc -lm

if [ $? -eq 0 ]
then 
	echo "Compile successful"
else	
	echo "failed"
fi
